### ISSUE TITLE
Error Found

### ISSUE THREAD

**Issue by ghost** [JoeTac/Takit-DNS#6]
[16:34:52 WARN]: [Takit-DNS] http://troybenson.za@gmail.com:******@dynupdate.no-ip.com/nic/update?hostname=blazedaze.servegame.com&myip=41.135.184.253 was not found.
[16:34:52 WARN]: Exception in thread "pool-3-thread-1898" 
[16:34:52 WARN]: org.apache.commons.lang.UnhandledException: Plugin Takit-DNS v0.3.3b generated an exception while executing task 4
        at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NullPointerException
        at org.takit.dns.services.NoIp.run(NoIp.java:30)
        at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:53)
        at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by ghost** [comment]
plz help
